package com.mgas.formation.enumeration;

public enum Service_ENUM {HR_SERVICE, CS_SERVICE, LEGAL_REGULATORY, INTERNAL_CONTROL, GENERAL_RESOURCES, AF_MANAGEMENT, OP_MANAGEMENT, MD_MANAGEMENT, JRPD_MANAGEMENT}